<a href="https://colab.research.google.com/github/Jeel88/DSV_Finance/blob/main/Finance_DSV_Project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [229]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [230]:
import kagglehub
path = kagglehub.dataset_download("danielsowah123/finance-and-banking")

Using Colab cache for faster access to the 'finance-and-banking' dataset.

In [231]:
df = pd.read_csv("/kaggle/input/finance-and-banking/finance_banking_transactions_2022_2025.csv")
df.head()

,transaction_id,account_id,customer_id,customer_name,account_type,account_status,transaction_type,transaction_date,amount,currency,...,is_international,fee_amount,risk_score,fraud_flag,aml_check_status,kyc_status,credit_score,customer_segment,ip_address,created_at
0,TXN-20230000000,ACC-229636759,CUST-616210,Sabine Koch,Checking,Frozen,Transfer,2025-06-14,17101.85,PLN,...,False,0.00,6.28,False,Failed,Pending,592.0,Premium,206.241.176.171,2023-01-13 12:32:00
1,TXN-20230000001,ACC-856806426,CUST-754810,Daniel Boateng,Loan,Frozen,Refund,2022-08-18,45026.38,USD,...,True,0.00,60.60,False,Passed,Expired,686.0,Private Banking,221.29.175.160,2023-02-26 08:58:00
2,TXN-20230000002,ACC-443163624,CUST-644966,Lukas Koch,Credit Card,Closed,Fee,2023-05-18,10658.79,EUR,...,True,0.00,97.67,False,Pending,Expired,763.0,Corporate,199.1.62.209,2023-07-10 15:28:00
3,TXN-20230000003,ACC-949045770,CUST-365821,Mia Weber,Credit Card,active,Interest,2023-09-22,-44113.52,PLN,...,True,13.33,71.52,True,Pending,Pending,388.0,Business,1.156.52.54,2023-02-25 07:14:00
4,TXN-20230000004,ACC-696055802,CUST-161490,Hanna Muller,Mortgage,Closed,Transfer,2022-05-29,-38955.13,CHF,...,True,7.44,51.16,True,Passed,verified,NaN,Corporate,69.62.158.212,2023-03-05 05:06:00

In [232]:
df.tail()

,transaction_id,account_id,customer_id,customer_name,account_type,account_status,transaction_type,transaction_date,amount,currency,...,is_international,fee_amount,risk_score,fraud_flag,aml_check_status,kyc_status,credit_score,customer_segment,ip_address,created_at
52619,TXN-20230014029,ACC-653025656,CUST-334886,Christina Sowah,Credit Card,Frozen,Payment,02-10-2022,5753.41,EUR,...,True,0.00,87.58,False,passed,Verified,NaN,Private Banking,9.191.163.119,2023-05-25 20:00:00
52620,TXN-20230039166,ACC-755323946,CUST-152217,Lukas Bauer,Mortgage,ACTIVE,Payment,2023-03-03,-36721.89,EUR,...,True,0.00,49.35,False,Skipped,Verified,546.0,Business,21.201.94.210,2023-07-17 05:00:00
52621,TXN-20230044663,ACC-970876882,CUST-187736,Paul Becker,Investment,Dormant,Payment,30/09/2023,49127.14,EUR,...,True,22.91,17.89,True,Pending,Verified,319.0,Premium,222.99.169.230,2023-03-19 20:55:00
52622,TXN-20230003784,ACC-712988228,CUST-657814,Paul Boateng,Credit Card,Active,Deposit,10 Apr 2023,38328.82,USD,...,True,0.00,39.75,False,Passed,Pending,666.0,Private Banking,197.215.46.180,2023-12-25 18:45:00
52623,TXN-20230000710,ACC-619154472,CUST-795395,David Agyeman,Checking,ACTIVE,Transfer,2025-11-19,-48822.90,PLN,...,True,0.00,6.57,False,Passed,Not Required,684.0,Retail,27.212.99.108,2023-03-23 17:37:00

In [233]:
df.shape

(52624, 25)

In [234]:
df.columns

Index(['transaction_id', 'account_id', 'customer_id', 'customer_name',
       'account_type', 'account_status', 'transaction_type',
       'transaction_date', 'amount', 'currency', 'balance_after',
       'transaction_channel', 'branch_city', 'merchant_name', 'payment_method',
       'is_international', 'fee_amount', 'risk_score', 'fraud_flag',
       'aml_check_status', 'kyc_status', 'credit_score', 'customer_segment',
       'ip_address', 'created_at'],
      dtype='object')

In [235]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 52624 entries, 0 to 52623
Data columns (total 25 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   transaction_id       52624 non-null  object
 1   account_id           52624 non-null  object
 2   customer_id          52624 non-null  object
 3   customer_name        52624 non-null  object
 4   account_type         52624 non-null  object
 5   account_status       52624 non-null  object
 6   transaction_type     52624 non-null  object
 7   transaction_date     52624 non-null  object
 8   amount               52624 non-null  float64
 9   currency             52624 non-null  object
 10  balance_after        52624 non-null  float64
 11  transaction_channel  52624 non-null  object
 12  branch_city          52624 non-null  object
 13  merchant_name        45378 non-null  object
 14  payment_method       52624 non-null  object
 15  is_international     52624 non-null  bool
 16  fee_amount           52624 non-null  float64
 17  risk_score           52624 non-null  float64
 18  fraud_flag           52624 non-null  bool
 19  aml_check_status     52624 non-null  object
 20  kyc_status           52624 non-null  object
 21  credit_score         35451 non-null  float64
 22  customer_segment     52624 non-null  object
 23  ip_address           52624 non-null  object
 24  created_at           52624 non-null  object
dtypes: bool(2), float64(5), object(18)
memory usage: 9.3+ MB

In [236]:
df.dtypes

transaction_id          object
account_id              object
customer_id             object
customer_name           object
account_type            object
account_status          object
transaction_type        object
transaction_date        object
amount                 float64
currency                object
balance_after          float64
transaction_channel     object
branch_city             object
merchant_name           object
payment_method          object
is_international          bool
fee_amount             float64
risk_score             float64
fraud_flag                bool
aml_check_status        object
kyc_status              object
credit_score           float64
customer_segment        object
ip_address              object
created_at              object
dtype: object

In [237]:
df.describe()

             amount  balance_after    fee_amount    risk_score  credit_score
count  5.262400e+04   52624.000000  52624.000000  52624.000000  35451.000000
mean   3.410845e+02  249109.767285      4.987369     49.909147    575.440665
std    9.579583e+04  143924.039306      7.633166     28.903701    159.012992
min   -4.737987e+06     107.180000      0.000000      0.010000    300.000000
25%   -2.515991e+04  124249.140000      0.000000     24.820000    438.000000
50%    3.244000e+01  248935.860000      0.000000     49.940000    576.000000
75%    2.524350e+04  373188.482500      9.400000     74.920000    713.000000
max    4.091722e+06  499987.450000     25.000000    100.000000    850.000000

In [238]:
df.isnull()

,transaction_id,account_id,customer_id,customer_name,account_type,account_status,transaction_type,transaction_date,amount,currency,...,is_international,fee_amount,risk_score,fraud_flag,aml_check_status,kyc_status,credit_score,customer_segment,ip_address,created_at
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,True,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
52619,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,True,False,False,False
52620,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
52621,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
52622,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
52623,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [239]:
df.isnull()

,transaction_id,account_id,customer_id,customer_name,account_type,account_status,transaction_type,transaction_date,amount,currency,...,is_international,fee_amount,risk_score,fraud_flag,aml_check_status,kyc_status,credit_score,customer_segment,ip_address,created_at
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,True,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
52619,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,True,False,False,False
52620,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
52621,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
52622,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
52623,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [240]:
df.isnull().sum()

transaction_id             0
account_id                 0
customer_id                0
customer_name              0
account_type               0
account_status             0
transaction_type           0
transaction_date           0
amount                     0
currency                   0
balance_after              0
transaction_channel        0
branch_city                0
merchant_name           7246
payment_method             0
is_international           0
fee_amount                 0
risk_score                 0
fraud_flag                 0
aml_check_status           0
kyc_status                 0
credit_score           17173
customer_segment           0
ip_address                 0
created_at                 0
dtype: int64

In [241]:
df['credit_score']=df['credit_score'].fillna(df['credit_score'].mean())

In [242]:
df.isnull().sum()

transaction_id            0
account_id                0
customer_id               0
customer_name             0
account_type              0
account_status            0
transaction_type          0
transaction_date          0
amount                    0
currency                  0
balance_after             0
transaction_channel       0
branch_city               0
merchant_name          7246
payment_method            0
is_international          0
fee_amount                0
risk_score                0
fraud_flag                0
aml_check_status          0
kyc_status                0
credit_score              0
customer_segment          0
ip_address                0
created_at                0
dtype: int64

In [243]:
df= df.dropna()

In [244]:
df.isnull().sum()

transaction_id         0
account_id             0
customer_id            0
customer_name          0
account_type           0
account_status         0
transaction_type       0
transaction_date       0
amount                 0
currency               0
balance_after          0
transaction_channel    0
branch_city            0
merchant_name          0
payment_method         0
is_international       0
fee_amount             0
risk_score             0
fraud_flag             0
aml_check_status       0
kyc_status             0
credit_score           0
customer_segment       0
ip_address             0
created_at             0
dtype: int64

In [245]:
df.isnull().sum().sum()

np.int64(0)

In [246]:
dc=df[df['transaction_id'].duplicated()]

In [247]:
df.duplicated().sum()

np.int64(543)

In [248]:
df[df.duplicated()]

,transaction_id,account_id,customer_id,customer_name,account_type,account_status,transaction_type,transaction_date,amount,currency,...,is_international,fee_amount,risk_score,fraud_flag,aml_check_status,kyc_status,credit_score,customer_segment,ip_address,created_at
52000,TXN-20230004774,ACC-715158530,CUST-880085,Felix Schneider,Savings,Dormant,Withdrawal,2023-09-30,-1987.42,GBP,...,False,17.36,15.57,False,Pending,Not Required,535.000000,Retail,246.125.201.129,2023-03-24 15:13:00
52001,TXN-20230009906,ACC-478409872,CUST-664476,Thomas Schmidt,Checking,ACTIVE,Fee,2024-06-05,11242.83,PLN,...,True,5.00,91.09,True,Skipped,Not Required,575.440665,Retail,155.59.252.225,2023-02-26 02:57:00
52003,TXN-20230020898,ACC-345760348,CUST-280438,Sabine Schmidt,Credit Card,Dormant,Transfer,2023-12-30,31182.45,PLN,...,True,0.00,64.82,False,Failed,Pending,378.000000,Business,194.12.60.245,2023-08-05 03:41:00
52005,TXN-20230001716,ACC-186493999,CUST-966763,Emma Sowah,Checking,active,Deposit,2022-12-11,11640.62,CHF,...,False,0.00,40.66,True,passed,Not Required,458.000000,Business,119.141.197.157,2023-01-28 17:57:00
52006,TXN-20230021959,ACC-511319351,CUST-350662,Leon Richter,Loan,active,Payment,2022-11-11,31465.20,GBP,...,True,0.00,89.30,False,Skipped,verified,440.000000,Business,52.45.162.65,2023-11-04 05:53:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
52619,TXN-20230014029,ACC-653025656,CUST-334886,Christina Sowah,Credit Card,Frozen,Payment,02-10-2022,5753.41,EUR,...,True,0.00,87.58,False,passed,Verified,575.440665,Private Banking,9.191.163.119,2023-05-25 20:00:00
52620,TXN-20230039166,ACC-755323946,CUST-152217,Lukas Bauer,Mortgage,ACTIVE,Payment,2023-03-03,-36721.89,EUR,...,True,0.00,49.35,False,Skipped,Verified,546.000000,Business,21.201.94.210,2023-07-17 05:00:00
52621,TXN-20230044663,ACC-970876882,CUST-187736,Paul Becker,Investment,Dormant,Payment,30/09/2023,49127.14,EUR,...,True,22.91,17.89,True,Pending,Verified,319.000000,Premium,222.99.169.230,2023-03-19 20:55:00
52622,TXN-20230003784,ACC-712988228,CUST-657814,Paul Boateng,Credit Card,Active,Deposit,10 Apr 2023,38328.82,USD,...,True,0.00,39.75,False,Passed,Pending,666.000000,Private Banking,197.215.46.180,2023-12-25 18:45:00
52623,TXN-20230000710,ACC-619154472,CUST-795395,David Agyeman,Checking,ACTIVE,Transfer,2025-11-19,-48822.90,PLN,...,True,0.00,6.57,False,Passed,Not Required,684.000000,Retail,27.212.99.108,2023-03-23 17:37:00

In [249]:
df['transaction_id'].duplicated().sum()

np.int64(543)

In [250]:
df=df.drop_duplicates()

In [251]:
df.duplicated().sum()

np.int64(0)

In [252]:
df.describe(include='all')

,transaction_id,account_id,customer_id,customer_name,account_type,account_status,transaction_type,transaction_date,amount,currency,...,is_international,fee_amount,risk_score,fraud_flag,aml_check_status,kyc_status,credit_score,customer_segment,ip_address,created_at
count,44835,44835,44835,44835,44835,44835,44835,44835,4.483500e+04,44835,...,44835,44835.000000,44835.000000,44835,44835,44835,44835.000000,44835,44835,44835
unique,44835,44835,43723,400,6,6,7,6021,NaN,5,...,2,NaN,NaN,2,6,5,NaN,5,44835,42847
top,TXN-20230051998,ACC-858737439,CUST-705125,Paul Richter,Investment,active,Payment,2023-04-29,NaN,EUR,...,False,NaN,NaN,False,Passed,verified,NaN,Business,166.42.248.105,2023-11-06 11:46:00
freq,1,1,3,138,7635,7655,6487,41,NaN,9047,...,22428,NaN,NaN,22452,7579,9067,NaN,9066,1,4
mean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.897083e+02,NaN,...,NaN,4.988099,49.898964,NaN,NaN,NaN,575.375580,NaN,NaN,NaN
std,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.509846e+04,NaN,...,NaN,7.635376,28.881505,NaN,NaN,NaN,130.449835,NaN,NaN,NaN
min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-4.737987e+06,NaN,...,NaN,0.000000,0.010000,NaN,NaN,NaN,300.000000,NaN,NaN,NaN
25%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-2.512417e+04,NaN,...,NaN,0.000000,24.850000,NaN,NaN,NaN,504.000000,NaN,NaN,NaN
50%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000e+00,NaN,...,NaN,0.000000,49.890000,NaN,NaN,NaN,575.440665,NaN,NaN,NaN
75%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.528101e+04,NaN,...,NaN,9.400000,74.910000,NaN,NaN,NaN,645.000000,NaN,NaN,NaN
max,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.091722e+06,NaN,...,NaN,25.000000,100.000000,NaN,NaN,NaN,850.000000,NaN,NaN,NaN

In [253]:
df['account_type'].unique()

array(['Checking', 'Loan', 'Credit Card', 'Mortgage', 'Savings',
       'Investment'], dtype=object)

In [254]:
df['transaction_type'].unique()

array(['Transfer', 'Refund', 'Fee', 'Interest', 'Deposit', 'Payment',
       'Withdrawal'], dtype=object)

In [255]:
df['payment_method'].unique()

array(['SEPA', 'sepa', 'Cash', 'Bank Transfer', 'Debit Card',
       'Credit Card'], dtype=object)

In [256]:
df['customer_segment'].unique()

array(['Premium', 'Private Banking', 'Corporate', 'Business', 'Retail'],
      dtype=object)

In [257]:
df['transaction_date']

0        2025-06-14
1        2022-08-18
2        2023-05-18
3        2023-09-22
5        2023-01-09
            ...
51993    2024-12-08
51994    2023-04-16
51995    2025-02-18
51996    2022-03-07
51998    21/05/2025
Name: transaction_date, Length: 44835, dtype: object

In [264]:
df['transaction_date'] = pd.to_datetime(df['transaction_date'],format='mixed')

In [267]:
df['transaction_date']= df['transaction_date'].dt.strftime('%d-%m-%Y')

In [268]:
df['transaction_date']

0        14-06-2025
1        18-08-2022
2        18-05-2023
3        22-09-2023
5        01-09-2023
            ...
51993    12-08-2024
51994    16-04-2023
51995    18-02-2025
51996    03-07-2022
51998    21-05-2025
Name: transaction_date, Length: 44835, dtype: object