<a href="https://colab.research.google.com/github/Jeel88/DSV_Finance/blob/main/Finance_DSV_Project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [10]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [11]:
import kagglehub
path = kagglehub.dataset_download("danielsowah123/finance-and-banking")

Using Colab cache for faster access to the 'finance-and-banking' dataset.

In [12]:
df = pd.read_csv("/kaggle/input/finance-and-banking/finance_banking_transactions_2022_2025.csv")
df.head()

,transaction_id,account_id,customer_id,customer_name,account_type,account_status,transaction_type,transaction_date,amount,currency,...,is_international,fee_amount,risk_score,fraud_flag,aml_check_status,kyc_status,credit_score,customer_segment,ip_address,created_at
0,TXN-20230000000,ACC-229636759,CUST-616210,Sabine Koch,Checking,Frozen,Transfer,2025-06-14,17101.85,PLN,...,False,0.00,6.28,False,Failed,Pending,592.0,Premium,206.241.176.171,2023-01-13 12:32:00
1,TXN-20230000001,ACC-856806426,CUST-754810,Daniel Boateng,Loan,Frozen,Refund,2022-08-18,45026.38,USD,...,True,0.00,60.60,False,Passed,Expired,686.0,Private Banking,221.29.175.160,2023-02-26 08:58:00
2,TXN-20230000002,ACC-443163624,CUST-644966,Lukas Koch,Credit Card,Closed,Fee,2023-05-18,10658.79,EUR,...,True,0.00,97.67,False,Pending,Expired,763.0,Corporate,199.1.62.209,2023-07-10 15:28:00
3,TXN-20230000003,ACC-949045770,CUST-365821,Mia Weber,Credit Card,active,Interest,2023-09-22,-44113.52,PLN,...,True,13.33,71.52,True,Pending,Pending,388.0,Business,1.156.52.54,2023-02-25 07:14:00
4,TXN-20230000004,ACC-696055802,CUST-161490,Hanna Muller,Mortgage,Closed,Transfer,2022-05-29,-38955.13,CHF,...,True,7.44,51.16,True,Passed,verified,NaN,Corporate,69.62.158.212,2023-03-05 05:06:00

In [17]:
df.tail()

,transaction_id,account_id,customer_id,customer_name,account_type,account_status,transaction_type,transaction_date,amount,currency,...,is_international,fee_amount,risk_score,fraud_flag,aml_check_status,kyc_status,credit_score,customer_segment,ip_address,created_at
52619,TXN-20230014029,ACC-653025656,CUST-334886,Christina Sowah,Credit Card,Frozen,Payment,02-10-2022,5753.41,EUR,...,True,0.00,87.58,False,passed,Verified,NaN,Private Banking,9.191.163.119,2023-05-25 20:00:00
52620,TXN-20230039166,ACC-755323946,CUST-152217,Lukas Bauer,Mortgage,ACTIVE,Payment,2023-03-03,-36721.89,EUR,...,True,0.00,49.35,False,Skipped,Verified,546.0,Business,21.201.94.210,2023-07-17 05:00:00
52621,TXN-20230044663,ACC-970876882,CUST-187736,Paul Becker,Investment,Dormant,Payment,30/09/2023,49127.14,EUR,...,True,22.91,17.89,True,Pending,Verified,319.0,Premium,222.99.169.230,2023-03-19 20:55:00
52622,TXN-20230003784,ACC-712988228,CUST-657814,Paul Boateng,Credit Card,Active,Deposit,10 Apr 2023,38328.82,USD,...,True,0.00,39.75,False,Passed,Pending,666.0,Private Banking,197.215.46.180,2023-12-25 18:45:00
52623,TXN-20230000710,ACC-619154472,CUST-795395,David Agyeman,Checking,ACTIVE,Transfer,2025-11-19,-48822.90,PLN,...,True,0.00,6.57,False,Passed,Not Required,684.0,Retail,27.212.99.108,2023-03-23 17:37:00

In [18]:
df.shape

(52624, 25)

In [19]:
df.columns

Index(['transaction_id', 'account_id', 'customer_id', 'customer_name',
       'account_type', 'account_status', 'transaction_type',
       'transaction_date', 'amount', 'currency', 'balance_after',
       'transaction_channel', 'branch_city', 'merchant_name', 'payment_method',
       'is_international', 'fee_amount', 'risk_score', 'fraud_flag',
       'aml_check_status', 'kyc_status', 'credit_score', 'customer_segment',
       'ip_address', 'created_at'],
      dtype='object')

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 52624 entries, 0 to 52623
Data columns (total 25 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   transaction_id       52624 non-null  object
 1   account_id           52624 non-null  object
 2   customer_id          52624 non-null  object
 3   customer_name        52624 non-null  object
 4   account_type         52624 non-null  object
 5   account_status       52624 non-null  object
 6   transaction_type     52624 non-null  object
 7   transaction_date     52624 non-null  object
 8   amount               52624 non-null  float64
 9   currency             52624 non-null  object
 10  balance_after        52624 non-null  float64
 11  transaction_channel  52624 non-null  object
 12  branch_city          52624 non-null  object
 13  merchant_name        45378 non-null  object
 14  payment_method       52624 non-null  object
 15  is_international     52624 non-null  bool
 16  fee_amount           52624 non-null  float64
 17  risk_score           52624 non-null  float64
 18  fraud_flag           52624 non-null  bool
 19  aml_check_status     52624 non-null  object
 20  kyc_status           52624 non-null  object
 21  credit_score         35451 non-null  float64
 22  customer_segment     52624 non-null  object
 23  ip_address           52624 non-null  object
 24  created_at           52624 non-null  object
dtypes: bool(2), float64(5), object(18)
memory usage: 9.3+ MB

In [22]:
df.dtypes

transaction_id          object
account_id              object
customer_id             object
customer_name           object
account_type            object
account_status          object
transaction_type        object
transaction_date        object
amount                 float64
currency                object
balance_after          float64
transaction_channel     object
branch_city             object
merchant_name           object
payment_method          object
is_international          bool
fee_amount             float64
risk_score             float64
fraud_flag                bool
aml_check_status        object
kyc_status              object
credit_score           float64
customer_segment        object
ip_address              object
created_at              object
dtype: object

In [23]:
df.describe()

             amount  balance_after    fee_amount    risk_score  credit_score
count  5.262400e+04   52624.000000  52624.000000  52624.000000  35451.000000
mean   3.410845e+02  249109.767285      4.987369     49.909147    575.440665
std    9.579583e+04  143924.039306      7.633166     28.903701    159.012992
min   -4.737987e+06     107.180000      0.000000      0.010000    300.000000
25%   -2.515991e+04  124249.140000      0.000000     24.820000    438.000000
50%    3.244000e+01  248935.860000      0.000000     49.940000    576.000000
75%    2.524350e+04  373188.482500      9.400000     74.920000    713.000000
max    4.091722e+06  499987.450000     25.000000    100.000000    850.000000

In [25]:
df.isnull()

,transaction_id,account_id,customer_id,customer_name,account_type,account_status,transaction_type,transaction_date,amount,currency,...,is_international,fee_amount,risk_score,fraud_flag,aml_check_status,kyc_status,credit_score,customer_segment,ip_address,created_at
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,True,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
52619,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,True,False,False,False
52620,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
52621,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
52622,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
52623,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [26]:
df.isnull().sum()

transaction_id             0
account_id                 0
customer_id                0
customer_name              0
account_type               0
account_status             0
transaction_type           0
transaction_date           0
amount                     0
currency                   0
balance_after              0
transaction_channel        0
branch_city                0
merchant_name           7246
payment_method             0
is_international           0
fee_amount                 0
risk_score                 0
fraud_flag                 0
aml_check_status           0
kyc_status                 0
credit_score           17173
customer_segment           0
ip_address                 0
created_at                 0
dtype: int64